### ISSUE TITLE
download pipe broken

### ISSUE THREAD

**Issue by irisyupingren** [pbrisbin/vagrant-haskell#1]
Downloading: http://files.vagrantup.com/lucid64.box
Stuck at 0%

**Comment by pbrisbin** [comment]
Hi there- I haven't used this project in years (`stack` and `docker` are both much more mature these days) and don't plan on maintaining it. Therefore, I'm going to archive it. I apologize if (somehow, despite the lack of maintenance) you've been relying on it.
